//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCeviri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ceviri2
    {
        public int id { get; set; }
        public string ingilizce { get; set; }
        public string turkce { get; set; }
    }
}
